remote_theme: pages-themes/hacker@v0.2.0
show_downloads: false
title: Support SIO1
description: 2024-2025
github:
  is_project_page: false
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
